### ISSUE TITLE
Weird crash after updating from 0.5.0 to 0.5.1

### ISSUE THREAD

**Issue by vico93** [jellysquid3/Sodium#2007]
### Bug Description

Basically, after updating Sodium to 0.5.1, Indium to 1.0.23 and Sodium Extra to build 112 i got this weird *Shader compilation failed* error and a crash.

I've uploaded both the crash report and the `latest.log` to a gist, to not let this issue text to be long.

### Reproduction Steps

- Update [Sodium](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.1), [Sodium Extra](https://modrinth.com/mod/sodium-extra/version/mc1.20.1-0.5.1) and [Indium](https://modrinth.com/mod/indium/version/1.0.24+mc1.20.1) to the linked versions;
- Open the game and try to load an existing world;
- The crash happens

### Log File

On [GIST](https://gist.github.com/vico93/313e4ceb76fdf3c7dcb7364f99dd1467) alongside the crash report.

### Crash Report

On [GIST](https://gist.github.com/vico93/313e4ceb76fdf3c7dcb7364f99dd1467) alongside the latest.log.

**Comment by pajicadvance** [comment]
It's caused by ChunksFadeIn. It needs an update to support Sodium 0.5.1.

**Comment by vico93** [comment]
> It's caused by ChunksFadeIn. It needs an update to support Sodium 0.5.1.

Thanks a lot for the clarification!
