### ISSUE TITLE
The game crashed whilst unexpected error Error: java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null Exit Code: -1

### ISSUE THREAD

**Issue by Jatin-Y** [jellysquid3/Sodium#1254]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Reproduction Steps

1. I load into the game
2. It loads everything fine, I can access settings and change them 
3. I join a multiplayer or Singleplayer World
4. The game says joining world or 100% then crashes (just exits out giving the error written in title)

### Crash Report file

---- Minecraft Crash Report ----
// There are four lights!

Time: 4/1/22, 7:50 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1007)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1007)

-- Affected level --
Details:
	All players: 16 total; [class_745['Iiqsm'/69818, l='ClientLevel', x=11.19, y=40.47, z=6.16], class_745[''/70033, l='ClientLevel', x=10.50, y=63.00, z=1.50], class_745['2360942095'/432, l='ClientLevel', x=24.50, y=64.00, z=10.50], class_745['55ng8u9157'/70, l='ClientLevel', x=26.50, y=64.00, z=4.50], class_745['8dv5304ttz'/72, l='ClientLevel', x=25.50, y=64.00, z=7.50], class_745['rail1811'/69811, l='ClientLevel', x=10.38, y=42.00, z=21.00], class_745['smozu'/69776, l='ClientLevel', x=0.25, y=65.41, z=-7.38], class_745['fenkiy'/69793, l='ClientLevel', x=4.22, y=64.50, z=-0.81], class_745['CAMAPA'/70032, l='ClientLevel', x=11.66, y=63.00, z=-3.25], class_745['544181fa16'/427, l='ClientLevel', x=9.50, y=63.00, z=-5.50], class_745['H0lly0ff_'/69761, l='ClientLevel', x=26.78, y=63.00, z=-0.22], class_745['nr1wn725bp'/61, l='ClientLevel', x=22.50, y=63.00, z=-15.50], class_745['w7082sg0j1'/68, l='ClientLevel', x=24.50, y=64.00, z=-9.50], class_745['qvk2nj8a5s'/69, l='ClientLevel', x=25.50, y=64.00, z=-6.50], class_745['br05zq864x'/71, l='ClientLevel', x=26.50, y=64.00, z=-3.50], class_745['waliee'/69821, l='ClientLevel', x=31.50, y=64.00, z=26.72]]
	Chunk stats: 16384, 169 F: 0 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,1), Section: (at 0,1,1 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 277114705 game time, 981 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman, 1.18.1 Tweak MAIN .zip, Tissou's+Zombie+Pack+1.18_2.1.zip, FreshAnimations_v1.6.zip, xali's+Potions+v1.0.zip, Enchanted+Tools+v2.6.zip, continuity/default, continuity/glass_pane_culling_fix, Magical_Bookshelves_(v1).zip, Particles+V.1.1.1.zip, Wildfire+2.0+-+1.18.zip, Fancy_Beds-1.18.zip, BlinkingEnderEyes_1.18_v2.zip, chests-to-pouches (1).zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1065743584 bytes (1016 MiB) / 1476395008 bytes (1408 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.39
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1616
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4531
	Graphics card #1 name: AMD Radeon R7 M265 Series
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x6604
	Graphics card #1 versionInfo: DriverVersion=27.20.20903.8001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 18730.46
	Virtual memory used (MB): 9228.56
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		alternatecurrent: Alternate Current 1.1.0
		antighost: AntiGhost 1.18.2-fabric0.47.10-1.1.4
		betterfpsdist: Better FPS distance Mod 1.18-1.5
		bobby: Bobby 3.1.1
		cameraoverhaul: Camera Overhaul 1.3.0-fabric-universal
		cem: Custom Entity Models 0.7.1
		charmonium: Charmonium 4.0.0
		chime: Chime 1.2.1
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cloth-api: Cloth API 3.2.64
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.2.64
		cloth-common-events-v1: Cloth Common Events v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
		cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
		cloth-utils-v1: Cloth Utils v1 3.2.64
		colormatic: Colormatic 3.1.1+mc.1.18.2
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.4.0
		continuity: Continuity 1.1.0+1.18.2
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		cullleaves: Cull Leaves 2.3.2
		customsplashscreen: Custom Splash Screen 1.2.0
		dashloader: DashLoader 3.1.1+1.18
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		dynamicfps: Dynamic FPS 2.1.0
		eatinganimationid: Eating Animation 1.5
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
		entity-view-distance: Entity View Distance 1.0.1+1.18.2
		entity_texture_features: Entity Texture Features 2.6.0
		entityculling: EntityCulling-Fabric 1.5.0
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.2+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fabricskyboxes: FabricSkyBoxes 0.5.5
		fabrishot: Fabrishot ${version}
		farsight: Farsight Mod 1.18-1.8
		ferritecore: FerriteCore 4.2.0
		frex: FREX 6.0.242
		impactfulweather: Biome Particle Weather 2.3.4
		inventoryhud: Inventory HUD + 3.4.2
		io_leangen_geantyref_geantyref: geantyref 1.3.13
		io_vram_bitkit: bitkit 1.0.4
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		json-model-extensions: JSON Model Extensions 1.22.246
		krypton: Krypton 0.1.9
		ksyxis: Ksyxis 1.1
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.18.2
		modmanager: Mod Manager 1.2.3+1.18
		modmenu: Mod Menu 3.1.0
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		pride: Pride Lib 1.1.0+1.17
		sodium: Sodium 0.4.1+build.15
		spruceui: SpruceUI 3.3.0+1.17
		waterdripsound: Drip Sounds 1.18-0.3.0
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon R7 M265 Series GL version 3.2.14831 Core Profile Forward-Compatible Context 21.5.2 27.20.20903.8001, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, charmonium/journeyman, file/1.18.1 Tweak MAIN .zip, file/Tissou's+Zombie+Pack+1.18_2.1.zip, file/FreshAnimations_v1.6.zip, file/xali's+Potions+v1.0.zip (incompatible), file/Enchanted+Tools+v2.6.zip, continuity/default, continuity/glass_pane_culling_fix, file/Magical_Bookshelves_(v1).zip, file/Particles+V.1.1.1.zip, file/Wildfire+2.0+-+1.18.zip, file/Fancy_Beds-1.18.zip, file/BlinkingEnderEyes_1.18_v2.zip, file/chests-to-pouches (1).zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

### Additional information

This has not happened in any other version before 1.18.2

**Comment by BitBlitObviMormon** [comment]
I get this same error, but on Android 11 with the Zink (Vulkan) renderer. Disabling `Use Persistent Mapping` in the advanced options returns a shader compilation error instead. Vanilla 1.18.2 runs fine.

**Comment by ST-DDT** [comment]
I get the exact same issue with 
- sodium-fabric-mc1.18.2-0.4.1+build.15
- indium-1.0.3+mc1.18.2


indium-1.0.2+mc1.18.2 works perfectly fine

**Comment by MeeniMc** [comment]
Invalid report, this is due to using mismatching versions of the mods.

**Comment by UltorGuard** [comment]
Really?

**Comment by Bigmancozmo** [comment]
I get this same issue with ONLY Sodium

**Comment by MeeniMc** [comment]
Multiple reports so obviously there is more to it that I initially thought. I cannot replicate with a fresh install of 1.18.2/Sodium-0.4.1+build.15 (the latest official build for 1.18.2) that I just created today.

Things to try: 
* use Fabric loader 0.14.21 (the latest as of today, it works with 1.18.2)
* erase the fabric cache (`.fabric` directory in  the `.minecraft` game folder)

--- 
Digging a bit into it

net.minecraft.class_757.field_4015 is net.minecraft.client.render.GameRenderer.client
net.minecraft.class_310.field_1724 is net.minecraft.client.MinecraftClient.player
net.minecraft.class_746.field_3911 is net.minecraft.client.network.ClientPlayerEntity.lastNauseaStrength

this line looks like it caused it (this is Mojang code)
`        float f = MathHelper.lerp(tickDelta, this.client.player.lastNauseaStrength, this.client.player.nextNauseaStrength) * this.client.options.distortionEffectScale * this.client.options.distortionEffectScale;` because player is not yet initialized in your case (again, I cannot replicate, so that is were the track goes cold for me).

**Comment by Bigmancozmo** [comment]
My issue was the Cull Leaves mod, not with Sodium itself. 👍

**Comment by jellysquid3** [comment]
It's impossible to debug this issue. We need a client log file. If this problem is still happening, then open a new issue with a client log file + crash report.

**Comment by linkedtimelines** [comment]
my issue was the grasskiss mod

**Comment by linkedtimelines** [comment]
or if ur render distance is like 100 with the bobby mod and nvidium
